// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pfoygamosiishlxyxfrn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBmb3lnYW1vc2lpc2hseHl4ZnJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzODYwNDcsImV4cCI6MjA2MTk2MjA0N30.PkaXUGLm9F5alFcHg_hjqEI3KgIbgcf1CF4w4FgQcxg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);